# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspividZ7.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(557, 338)
        Form.setSizeIncrement(QtCore.QSize(50, 25))
        Form.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Vbrillance = QtGui.QSpinBox(Form)
        self.Vbrillance.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vbrillance.setMaximum(100)
        self.Vbrillance.setObjectName(_fromUtf8("Vbrillance"))
        self.gridLayout_2.addWidget(self.Vbrillance, 1, 3, 1, 1)
        self.Vpecran = QtGui.QComboBox(Form)
        self.Vpecran.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vpecran.setObjectName(_fromUtf8("Vpecran"))
        self.Vpecran.addItem(_fromUtf8(""))
        self.Vpecran.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vpecran, 0, 5, 1, 1)
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)
        self.hflip = QtGui.QLabel(Form)
        self.hflip.setObjectName(_fromUtf8("hflip"))
        self.gridLayout_2.addWidget(self.hflip, 5, 0, 1, 1)
        self.VLC = QtGui.QPushButton(Form)
        self.VLC.setStyleSheet(_fromUtf8("background-color: rgb(255, 124, 188);\n"
"border-top-color: rgb(0, 0, 0);"))
        self.VLC.setObjectName(_fromUtf8("VLC"))
        self.gridLayout_2.addWidget(self.VLC, 6, 3, 1, 1)
        self.Vduree = QtGui.QComboBox(Form)
        self.Vduree.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vduree.setObjectName(_fromUtf8("Vduree"))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.setItemText(1, _fromUtf8("1"))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.setItemText(2, _fromUtf8("2"))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.setItemText(3, _fromUtf8("5"))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.setItemText(4, _fromUtf8("10"))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.setItemText(5, _fromUtf8("15"))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.setItemText(6, _fromUtf8("30"))
        self.Vduree.addItem(_fromUtf8(""))
        self.Vduree.setItemText(7, _fromUtf8("60"))
        self.gridLayout_2.addWidget(self.Vduree, 0, 1, 1, 1)
        self.Vhauteur = QtGui.QComboBox(Form)
        self.Vhauteur.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vhauteur.setObjectName(_fromUtf8("Vhauteur"))
        self.Vhauteur.addItem(_fromUtf8(""))
        self.Vhauteur.addItem(_fromUtf8(""))
        self.Vhauteur.addItem(_fromUtf8(""))
        self.Vhauteur.addItem(_fromUtf8(""))
        self.Vhauteur.addItem(_fromUtf8(""))
        self.Vhauteur.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vhauteur, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 4, 1, 1)
        self.duree = QtGui.QLabel(Form)
        self.duree.setObjectName(_fromUtf8("duree"))
        self.gridLayout_2.addWidget(self.duree, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 4, 1, 1)
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.stabilite = QtGui.QLabel(Form)
        self.stabilite.setObjectName(_fromUtf8("stabilite"))
        self.gridLayout_2.addWidget(self.stabilite, 1, 0, 1, 1)
        self.Vmetadata = QtGui.QComboBox(Form)
        self.Vmetadata.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vmetadata.setObjectName(_fromUtf8("Vmetadata"))
        self.Vmetadata.addItem(_fromUtf8(""))
        self.Vmetadata.addItem(_fromUtf8(""))
        self.Vmetadata.addItem(_fromUtf8(""))
        self.Vmetadata.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vmetadata, 2, 5, 1, 1)
        self.VLargeur = QtGui.QComboBox(Form)
        self.VLargeur.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.VLargeur.setObjectName(_fromUtf8("VLargeur"))
        self.VLargeur.addItem(_fromUtf8(""))
        self.VLargeur.addItem(_fromUtf8(""))
        self.VLargeur.addItem(_fromUtf8(""))
        self.VLargeur.addItem(_fromUtf8(""))
        self.VLargeur.addItem(_fromUtf8(""))
        self.VLargeur.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.VLargeur, 4, 1, 1, 1)
        self.Vfinesse = QtGui.QSpinBox(Form)
        self.Vfinesse.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vfinesse.setMinimum(-100)
        self.Vfinesse.setMaximum(100)
        self.Vfinesse.setObjectName(_fromUtf8("Vfinesse"))
        self.gridLayout_2.addWidget(self.Vfinesse, 3, 3, 1, 1)
        self.effets = QtGui.QLabel(Form)
        self.effets.setObjectName(_fromUtf8("effets"))
        self.gridLayout_2.addWidget(self.effets, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 4, 1, 1)
        self.HDMI = QtGui.QPushButton(Form)
        self.HDMI.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.HDMI.setObjectName(_fromUtf8("HDMI"))
        self.gridLayout_2.addWidget(self.HDMI, 6, 5, 1, 1)
        self.Executer = QtGui.QPushButton(Form)
        self.Executer.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.Executer.setObjectName(_fromUtf8("Executer"))
        self.gridLayout_2.addWidget(self.Executer, 7, 5, 1, 1)
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.GSTREAM = QtGui.QPushButton(Form)
        self.GSTREAM.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);"))
        self.GSTREAM.setObjectName(_fromUtf8("GSTREAM"))
        self.gridLayout_2.addWidget(self.GSTREAM, 6, 4, 1, 1)
        self.Manuel = QtGui.QLabel(Form)
        self.Manuel.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        self.Manuel.setObjectName(_fromUtf8("Manuel"))
        self.gridLayout_2.addWidget(self.Manuel, 7, 1, 1, 1)
        self.largeur = QtGui.QLabel(Form)
        self.largeur.setEnabled(False)
        self.largeur.setObjectName(_fromUtf8("largeur"))
        self.gridLayout_2.addWidget(self.largeur, 4, 0, 1, 1)
        self.Vcontraste = QtGui.QSpinBox(Form)
        self.Vcontraste.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vcontraste.setMinimum(-100)
        self.Vcontraste.setMaximum(100)
        self.Vcontraste.setObjectName(_fromUtf8("Vcontraste"))
        self.gridLayout_2.addWidget(self.Vcontraste, 0, 3, 1, 1)
        self.Veffets = QtGui.QComboBox(Form)
        self.Veffets.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Veffets.setObjectName(_fromUtf8("Veffets"))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.Veffets.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Veffets, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 5, 2, 1, 1)
        self.Viso = QtGui.QComboBox(Form)
        self.Viso.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Viso.setObjectName(_fromUtf8("Viso"))
        self.Viso.addItem(_fromUtf8(""))
        self.Viso.addItem(_fromUtf8(""))
        self.Viso.addItem(_fromUtf8(""))
        self.Viso.addItem(_fromUtf8(""))
        self.Viso.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Viso, 3, 5, 1, 1)
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 4, 2, 1, 1)
        self.Vhflip = QtGui.QComboBox(Form)
        self.Vhflip.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vhflip.setObjectName(_fromUtf8("Vhflip"))
        self.Vhflip.addItem(_fromUtf8(""))
        self.Vhflip.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vhflip, 5, 1, 1, 1)
        self.Vcompression = QtGui.QComboBox(Form)
        self.Vcompression.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vcompression.setObjectName(_fromUtf8("Vcompression"))
        self.Vcompression.addItem(_fromUtf8(""))
        self.Vcompression.addItem(_fromUtf8(""))
        self.Vcompression.addItem(_fromUtf8(""))
        self.Vcompression.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vcompression, 4, 5, 1, 1)
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 4, 4, 1, 1)
        self.Vrotation = QtGui.QComboBox(Form)
        self.Vrotation.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vrotation.setObjectName(_fromUtf8("Vrotation"))
        self.Vrotation.addItem(_fromUtf8(""))
        self.Vrotation.addItem(_fromUtf8(""))
        self.Vrotation.addItem(_fromUtf8(""))
        self.Vrotation.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vrotation, 5, 3, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 4, 1, 1)
        self.Vvflip = QtGui.QComboBox(Form)
        self.Vvflip.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vvflip.setObjectName(_fromUtf8("Vvflip"))
        self.Vvflip.addItem(_fromUtf8(""))
        self.Vvflip.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vvflip, 5, 5, 1, 1)
        self.Vsaturation = QtGui.QSpinBox(Form)
        self.Vsaturation.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vsaturation.setMinimum(-100)
        self.Vsaturation.setMaximum(100)
        self.Vsaturation.setObjectName(_fromUtf8("Vsaturation"))
        self.gridLayout_2.addWidget(self.Vsaturation, 2, 3, 1, 1)
        self.sauvegarde = QtGui.QLabel(Form)
        self.sauvegarde.setObjectName(_fromUtf8("sauvegarde"))
        self.gridLayout_2.addWidget(self.sauvegarde, 6, 0, 1, 1)
        self.Vsauvegarde = QtGui.QLineEdit(Form)
        self.Vsauvegarde.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vsauvegarde.setObjectName(_fromUtf8("Vsauvegarde"))
        self.gridLayout_2.addWidget(self.Vsauvegarde, 6, 1, 1, 1)
        self.Vframerate = QtGui.QSpinBox(Form)
        self.Vframerate.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vframerate.setMinimum(2)
        self.Vframerate.setMaximum(30)
        self.Vframerate.setProperty("value", 25)
        self.Vframerate.setObjectName(_fromUtf8("Vframerate"))
        self.gridLayout_2.addWidget(self.Vframerate, 4, 3, 1, 1)
        self.Vstabilite = QtGui.QComboBox(Form)
        self.Vstabilite.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vstabilite.setObjectName(_fromUtf8("Vstabilite"))
        self.Vstabilite.addItem(_fromUtf8(""))
        self.Vstabilite.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vstabilite, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 4, 1, 1)
        self.hauteur = QtGui.QLabel(Form)
        self.hauteur.setObjectName(_fromUtf8("hauteur"))
        self.gridLayout_2.addWidget(self.hauteur, 3, 0, 1, 1)
        self.Vmode = QtGui.QComboBox(Form)
        self.Vmode.setStyleSheet(_fromUtf8("background-color: rgb(245, 194, 255);"))
        self.Vmode.setObjectName(_fromUtf8("Vmode"))
        self.Vmode.addItem(_fromUtf8(""))
        self.Vmode.addItem(_fromUtf8(""))
        self.Vmode.addItem(_fromUtf8(""))
        self.Vmode.addItem(_fromUtf8(""))
        self.Vmode.addItem(_fromUtf8(""))
        self.Vmode.addItem(_fromUtf8(""))
        self.Vmode.addItem(_fromUtf8(""))
        self.Vmode.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Vmode, 1, 5, 1, 1)
        self.visualisation = QtGui.QLabel(Form)
        self.visualisation.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.visualisation.setAlignment(QtCore.Qt.AlignCenter)
        self.visualisation.setObjectName(_fromUtf8("visualisation"))
        self.gridLayout_2.addWidget(self.visualisation, 9, 0, 1, 6)
        self.comfinale = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comfinale.setFont(font)
        self.comfinale.setStyleSheet(_fromUtf8("background-color: rgb(255, 158, 126);"))
        self.comfinale.setObjectName(_fromUtf8("comfinale"))
        self.gridLayout_2.addWidget(self.comfinale, 10, 0, 1, 6)
        self.RAZ = QtGui.QPushButton(Form)
        self.RAZ.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 0);"))
        self.RAZ.setObjectName(_fromUtf8("RAZ"))
        self.gridLayout_2.addWidget(self.RAZ, 7, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.Vduree.setCurrentIndex(3)
        self.Vhauteur.setCurrentIndex(1)
        self.VLargeur.setCurrentIndex(1)
        QtCore.QObject.connect(self.Vhauteur, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.VLargeur.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Parametres Raspivid", None))
        self.Vpecran.setItemText(0, _translate("Form", "inactif", None))
        self.Vpecran.setItemText(1, _translate("Form", "-f", None))
        self.label_15.setText(_translate("Form", "Finesse", None))
        self.label_10.setText(_translate("Form", "Saturation", None))
        self.hflip.setToolTip(_translate("Form", "<html><head/><body><p>Effet miroir horizontal</p></body></html>", None))
        self.hflip.setText(_translate("Form", "Hflip", None))
        self.VLC.setToolTip(_translate("Form", "<html><head/><body><p>serveur de Streaming VLC (latence 2s)</p></body></html>", None))
        self.VLC.setText(_translate("Form", "VLC", None))
        self.Vduree.setItemText(0, _translate("Form", "inactif", None))
        self.Vhauteur.setItemText(0, _translate("Form", "inactif", None))
        self.Vhauteur.setItemText(1, _translate("Form", "240", None))
        self.Vhauteur.setItemText(2, _translate("Form", "260", None))
        self.Vhauteur.setItemText(3, _translate("Form", "480", None))
        self.Vhauteur.setItemText(4, _translate("Form", "600", None))
        self.Vhauteur.setItemText(5, _translate("Form", "768", None))
        self.label_11.setText(_translate("Form", "Iso", None))
        self.duree.setToolTip(_translate("Form", "<html><head/><body><p>Durée de la vidéo en minutes</p><p><br/></p></body></html>", None))
        self.duree.setText(_translate("Form", "Durée", None))
        self.label_19.setToolTip(_translate("Form", "<html><head/><body><p>Définit un mode de capteur :</p><p><br/></p><p>0 : mode automatique</p><p>1 :1920 x 1080 ; aspect 16/9 ; 1-30 fps ; fov partiel ; binning non</p><p>2: 2592 x 1944 ; aspect 4/3 ; 1-15 fps ; fov full ; binning non</p><p>3: id 2 sauf fps 0,1666-1</p><p>4: 1296 x 972 ; aspect 4/3 ; 1-42 fps ; fov full ; binning 2x2</p><p>5: 1296 x 730 ; aspect 16/9 ; 1-49 fps; fov full ; binning 2 x2</p><p>6: 640 x 480 ; aspect 4/3 ; 42,1-60 fps ; fov full ; binning 2x2 plus skip</p><p>7: 640 x 480 ; aspect 4/3 ; 60,1-90 fps ; fov full ; binning 2x2 plus skip</p></body></html>", None))
        self.label_19.setText(_translate("Form", "Mode", None))
        self.label_13.setText(_translate("Form", "Contraste", None))
        self.stabilite.setToolTip(_translate("Form", "<html><head/><body><p>Stabilisation d\'image si la caméra bouge</p></body></html>", None))
        self.stabilite.setText(_translate("Form", "Stabilité", None))
        self.Vmetadata.setItemText(0, _translate("Form", "inactif", None))
        self.Vmetadata.setItemText(1, _translate("Form", "4", None))
        self.Vmetadata.setItemText(2, _translate("Form", "8", None))
        self.Vmetadata.setItemText(3, _translate("Form", "12", None))
        self.VLargeur.setItemText(0, _translate("Form", "inactif", None))
        self.VLargeur.setItemText(1, _translate("Form", "360", None))
        self.VLargeur.setItemText(2, _translate("Form", "480", None))
        self.VLargeur.setItemText(3, _translate("Form", "640", None))
        self.VLargeur.setItemText(4, _translate("Form", "800", None))
        self.VLargeur.setItemText(5, _translate("Form", "1024", None))
        self.effets.setToolTip(_translate("Form", "<html><head/><body><p>Sélectionne un effet appliqué à l\'image</p></body></html>", None))
        self.effets.setText(_translate("Form", "Effets", None))
        self.label_17.setToolTip(_translate("Form", "<html><head/><body><p>Données intégrées dans la vidéo </p><p>4 : heure</p><p>8: date</p><p>12 : heure+ date</p><p><br/></p></body></html>", None))
        self.label_17.setText(_translate("Form", "Metadata", None))
        self.HDMI.setToolTip(_translate("Form", "<html><head/><body><p>Visualisation directe de la vidéo sans streaming</p></body></html>", None))
        self.HDMI.setText(_translate("Form", "HDMI", None))
        self.Executer.setToolTip(_translate("Form", "<html><head/><body><p>Valide le choix d\'instructions et ferme la fenêtre.</p><p>La commande sélectionnée est enregistrée dans le fichier .sh correspondant pour le streaming</p></body></html>", None))
        self.Executer.setText(_translate("Form", "Executer", None))
        self.label_12.setText(_translate("Form", "Brillance", None))
        self.GSTREAM.setToolTip(_translate("Form", "<html><head/><body><p>Serveur de streaming Gstreamer (video temps reel)</p></body></html>", None))
        self.GSTREAM.setText(_translate("Form", "GSTREAM", None))
        self.Manuel.setToolTip(_translate("Form", "<html><head/><body><p>1/ selectionner les options désirées</p><p><br/></p><p>2/choisir :</p><p>HDMI : pour affichage video sur un écran branché au RPI</p><p>VLC pour un streaming vlc</p><p>GSTREAM pour un streaming gstreamer</p><p>NB : le champ sauvegarde ne sert qu\'à spécifier un nom de fichier pour un éventuelle enregistrement de la video</p><p>Il ne faut pas y mettre -o pour le streaming,cela se fait automatiquement</p><p><br/></p><p>La ligne de commande s\'affiche.</p><p><br/></p><p>3/ : en cas d\'erreur : RAZ reinitialise la ligne de commande</p><p><br/></p><p>4/ Executer : lance la video et ferme la fenêtre</p><p><br/></p></body></html>", None))
        self.Manuel.setText(_translate("Form", "Manuel", None))
        self.largeur.setToolTip(_translate("Form", "<html><head/><body><p>Largeur de la fenêtre de visualisation.Automatiquement générée lors du choix de la hauteur</p></body></html>", None))
        self.largeur.setText(_translate("Form", "Largeur", None))
        self.Veffets.setItemText(0, _translate("Form", "inactif", None))
        self.Veffets.setItemText(1, _translate("Form", "negative", None))
        self.Veffets.setItemText(2, _translate("Form", "solarise", None))
        self.Veffets.setItemText(3, _translate("Form", "posterise", None))
        self.Veffets.setItemText(4, _translate("Form", "whiteboard", None))
        self.Veffets.setItemText(5, _translate("Form", "blackboard", None))
        self.Veffets.setItemText(6, _translate("Form", "sketch", None))
        self.Veffets.setItemText(7, _translate("Form", "denoise", None))
        self.Veffets.setItemText(8, _translate("Form", "emboss", None))
        self.Veffets.setItemText(9, _translate("Form", "oilpaint", None))
        self.Veffets.setItemText(10, _translate("Form", "hatch", None))
        self.Veffets.setItemText(11, _translate("Form", "gpen", None))
        self.Veffets.setItemText(12, _translate("Form", "pastel", None))
        self.Veffets.setItemText(13, _translate("Form", "film", None))
        self.Veffets.setItemText(14, _translate("Form", "watercolour", None))
        self.Veffets.setItemText(15, _translate("Form", "blur", None))
        self.Veffets.setItemText(16, _translate("Form", "saturation", None))
        self.label_9.setText(_translate("Form", "Rotation", None))
        self.Viso.setItemText(0, _translate("Form", "inactif", None))
        self.Viso.setItemText(1, _translate("Form", "100", None))
        self.Viso.setItemText(2, _translate("Form", "200", None))
        self.Viso.setItemText(3, _translate("Form", "400", None))
        self.Viso.setItemText(4, _translate("Form", "800", None))
        self.label_16.setToolTip(_translate("Form", "<html><head/><body><p>nombre d\'images par seconde</p></body></html>", None))
        self.label_16.setText(_translate("Form", "Framerate", None))
        self.Vhflip.setItemText(0, _translate("Form", "inactif", None))
        self.Vhflip.setItemText(1, _translate("Form", " -hf ", None))
        self.Vcompression.setItemText(0, _translate("Form", "inactif", None))
        self.Vcompression.setItemText(1, _translate("Form", "low", None))
        self.Vcompression.setItemText(2, _translate("Form", "medium", None))
        self.Vcompression.setItemText(3, _translate("Form", "high", None))
        self.label_18.setToolTip(_translate("Form", "<html><head/><body><p><a name=\"result_box\"/>DRC (dynamic range compression) change les images en augmentant la plage des zones sombres et en diminuant les zones plus claires. Cela peut améliorer l\'image dans les zones de faible luminosité.</p></body></html>", None))
        self.label_18.setText(_translate("Form", "DRC", None))
        self.Vrotation.setItemText(0, _translate("Form", "inactif", None))
        self.Vrotation.setItemText(1, _translate("Form", "90", None))
        self.Vrotation.setItemText(2, _translate("Form", "180", None))
        self.Vrotation.setItemText(3, _translate("Form", "270", None))
        self.label_7.setToolTip(_translate("Form", "<html><head/><body><p>Effet miroir vertical</p></body></html>", None))
        self.label_7.setText(_translate("Form", "Vflip", None))
        self.Vvflip.setItemText(0, _translate("Form", "inactif", None))
        self.Vvflip.setItemText(1, _translate("Form", "-vf ", None))
        self.sauvegarde.setToolTip(_translate("Form", "<html><head/><body><p>Nom du fichier où enregistrer la vidéo si necéssaire.</p><p>pas de nom : pas d\'enregistrement </p><p>- (&quot;tiret du 6&quot;) : envoi vers stout</p></body></html>", None))
        self.sauvegarde.setText(_translate("Form", "Sauvegarde", None))
        self.Vstabilite.setItemText(0, _translate("Form", "inactif", None))
        self.Vstabilite.setItemText(1, _translate("Form", "-vs", None))
        self.label_14.setText(_translate("Form", "Plein ecran", None))
        self.hauteur.setToolTip(_translate("Form", "<html><head/><body><p>Hauteur de la fenêtre de visualisation</p><p><br/></p></body></html>", None))
        self.hauteur.setText(_translate("Form", "Hauteur", None))
        self.Vmode.setItemText(0, _translate("Form", "inactif", None))
        self.Vmode.setItemText(1, _translate("Form", "1", None))
        self.Vmode.setItemText(2, _translate("Form", "2", None))
        self.Vmode.setItemText(3, _translate("Form", "3", None))
        self.Vmode.setItemText(4, _translate("Form", "4", None))
        self.Vmode.setItemText(5, _translate("Form", "5", None))
        self.Vmode.setItemText(6, _translate("Form", "6", None))
        self.Vmode.setItemText(7, _translate("Form", "7", None))
        self.visualisation.setText(_translate("Form", "Commande resultante", None))
        self.comfinale.setText(_translate("Form", "raspivid", None))
        self.RAZ.setToolTip(_translate("Form", "<html><head/><body><p>Remise à zéro de la ligne de commande en cas d\'erreur</p></body></html>", None))
        self.RAZ.setText(_translate("Form", "RAZ", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

