# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intRaspibotDesign10.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InterfaceCommande(object):
    def setupUi(self, InterfaceCommande):
        InterfaceCommande.setObjectName(_fromUtf8("InterfaceCommande"))
        InterfaceCommande.resize(516, 658)
        self.moteurs = QtGui.QWidget(InterfaceCommande)
        self.moteurs.setGeometry(QtCore.QRect(250, 180, 260, 260))
        self.moteurs.setMouseTracking(False)
        self.moteurs.setStyleSheet(_fromUtf8("background-color: rgb(83, 249, 122);\n"
"selection-background-color: rgb(255, 0, 0);\n"
""))
        self.moteurs.setObjectName(_fromUtf8("moteurs"))
        self.line = QtGui.QFrame(self.moteurs)
        self.line.setGeometry(QtCore.QRect(105, 0, 20, 261))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.moteurs)
        self.line_2.setGeometry(QtCore.QRect(131, 0, 20, 261))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.moteurs)
        self.line_3.setGeometry(QtCore.QRect(-3, 135, 261, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.moteurs)
        self.line_4.setGeometry(QtCore.QRect(0, 109, 261, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.moteurs)
        self.line_5.setGeometry(QtCore.QRect(0, 9, 261, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.moteurs)
        self.line_6.setGeometry(QtCore.QRect(0, 235, 261, 21))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.clic = QtGui.QWidget(self.moteurs)
        self.clic.setGeometry(QtCore.QRect(50, 50, 3, 3))
        self.clic.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 0, 0);"))
        self.clic.setObjectName(_fromUtf8("clic"))
        self.gridLayoutWidget = QtGui.QWidget(InterfaceCommande)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 180, 241, 383))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.EBS = QtGui.QSlider(self.gridLayoutWidget)
        self.EBS.setMinimum(0)
        self.EBS.setMaximum(120)
        self.EBS.setProperty("value", 60)
        self.EBS.setSliderPosition(60)
        self.EBS.setOrientation(QtCore.Qt.Horizontal)
        self.EBS.setObjectName(_fromUtf8("EBS"))
        self.gridLayout.addWidget(self.EBS, 17, 2, 1, 1)
        self.EBLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.EBLabel.setObjectName(_fromUtf8("EBLabel"))
        self.gridLayout.addWidget(self.EBLabel, 14, 2, 1, 1)
        self.RAZgeneral = QtGui.QPushButton(self.gridLayoutWidget)
        self.RAZgeneral.setMaximumSize(QtCore.QSize(40, 16777215))
        self.RAZgeneral.setBaseSize(QtCore.QSize(0, 0))
        self.RAZgeneral.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 255);"))
        self.RAZgeneral.setObjectName(_fromUtf8("RAZgeneral"))
        self.gridLayout.addWidget(self.RAZgeneral, 0, 1, 1, 1)
        self.RBini = QtGui.QPushButton(self.gridLayoutWidget)
        self.RBini.setMaximumSize(QtCore.QSize(40, 16777215))
        self.RBini.setBaseSize(QtCore.QSize(0, 0))
        self.RBini.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 255);"))
        self.RBini.setObjectName(_fromUtf8("RBini"))
        self.gridLayout.addWidget(self.RBini, 11, 1, 1, 1)
        self.pinceini = QtGui.QPushButton(self.gridLayoutWidget)
        self.pinceini.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pinceini.setBaseSize(QtCore.QSize(0, 0))
        self.pinceini.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 255);"))
        self.pinceini.setObjectName(_fromUtf8("pinceini"))
        self.gridLayout.addWidget(self.pinceini, 21, 1, 1, 1)
        self.ElevBini = QtGui.QPushButton(self.gridLayoutWidget)
        self.ElevBini.setMaximumSize(QtCore.QSize(40, 16777215))
        self.ElevBini.setBaseSize(QtCore.QSize(0, 0))
        self.ElevBini.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 255);"))
        self.ElevBini.setObjectName(_fromUtf8("ElevBini"))
        self.gridLayout.addWidget(self.ElevBini, 17, 1, 1, 1)
        self.RotCini = QtGui.QPushButton(self.gridLayoutWidget)
        self.RotCini.setMaximumSize(QtCore.QSize(40, 16777215))
        self.RotCini.setBaseSize(QtCore.QSize(0, 0))
        self.RotCini.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.RotCini.setObjectName(_fromUtf8("RotCini"))
        self.gridLayout.addWidget(self.RotCini, 5, 1, 1, 1)
        self.PinceS = QtGui.QSlider(self.gridLayoutWidget)
        self.PinceS.setMinimum(0)
        self.PinceS.setMaximum(120)
        self.PinceS.setProperty("value", 60)
        self.PinceS.setSliderPosition(60)
        self.PinceS.setOrientation(QtCore.Qt.Horizontal)
        self.PinceS.setObjectName(_fromUtf8("PinceS"))
        self.gridLayout.addWidget(self.PinceS, 21, 2, 1, 1)
        self.RBS = QtGui.QSlider(self.gridLayoutWidget)
        self.RBS.setMinimum(0)
        self.RBS.setMaximum(120)
        self.RBS.setProperty("value", 60)
        self.RBS.setSliderPosition(60)
        self.RBS.setOrientation(QtCore.Qt.Horizontal)
        self.RBS.setObjectName(_fromUtf8("RBS"))
        self.gridLayout.addWidget(self.RBS, 11, 2, 1, 1)
        self.RAZLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.RAZLabel.setObjectName(_fromUtf8("RAZLabel"))
        self.gridLayout.addWidget(self.RAZLabel, 0, 2, 1, 1)
        self.AvArBS = QtGui.QSlider(self.gridLayoutWidget)
        self.AvArBS.setMinimum(0)
        self.AvArBS.setMaximum(120)
        self.AvArBS.setProperty("value", 60)
        self.AvArBS.setSliderPosition(60)
        self.AvArBS.setOrientation(QtCore.Qt.Horizontal)
        self.AvArBS.setInvertedAppearance(True)
        self.AvArBS.setInvertedControls(False)
        self.AvArBS.setObjectName(_fromUtf8("AvArBS"))
        self.gridLayout.addWidget(self.AvArBS, 13, 2, 1, 1)
        self.RCLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.RCLabel.setObjectName(_fromUtf8("RCLabel"))
        self.gridLayout.addWidget(self.RCLabel, 4, 2, 1, 1)
        self.RCVal = QtGui.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.RCVal.setFont(font)
        self.RCVal.setStyleSheet(_fromUtf8("background-color: rgb(99, 99, 99);"))
        self.RCVal.setNumDigits(3)
        self.RCVal.setProperty("intValue", 60)
        self.RCVal.setObjectName(_fromUtf8("RCVal"))
        self.gridLayout.addWidget(self.RCVal, 5, 3, 1, 1)
        self.ElevBVal = QtGui.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ElevBVal.setFont(font)
        self.ElevBVal.setStyleSheet(_fromUtf8("background-color: rgb(99, 99, 99);"))
        self.ElevBVal.setNumDigits(3)
        self.ElevBVal.setProperty("intValue", 60)
        self.ElevBVal.setObjectName(_fromUtf8("ElevBVal"))
        self.gridLayout.addWidget(self.ElevBVal, 17, 3, 1, 1)
        self.PinceVal = QtGui.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PinceVal.setFont(font)
        self.PinceVal.setStyleSheet(_fromUtf8("background-color: rgb(99, 99, 99);"))
        self.PinceVal.setNumDigits(3)
        self.PinceVal.setProperty("intValue", 60)
        self.PinceVal.setObjectName(_fromUtf8("PinceVal"))
        self.gridLayout.addWidget(self.PinceVal, 21, 3, 1, 1)
        self.RBVal = QtGui.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.RBVal.setFont(font)
        self.RBVal.setStyleSheet(_fromUtf8("background-color: rgb(99, 99, 99);"))
        self.RBVal.setNumDigits(3)
        self.RBVal.setProperty("intValue", 60)
        self.RBVal.setObjectName(_fromUtf8("RBVal"))
        self.gridLayout.addWidget(self.RBVal, 11, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(30, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.PinceLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.PinceLabel.setObjectName(_fromUtf8("PinceLabel"))
        self.gridLayout.addWidget(self.PinceLabel, 20, 2, 1, 1)
        self.RCS = QtGui.QSlider(self.gridLayoutWidget)
        self.RCS.setMinimum(0)
        self.RCS.setMaximum(120)
        self.RCS.setProperty("value", 60)
        self.RCS.setSliderPosition(60)
        self.RCS.setOrientation(QtCore.Qt.Horizontal)
        self.RCS.setObjectName(_fromUtf8("RCS"))
        self.gridLayout.addWidget(self.RCS, 5, 2, 1, 1)
        self.HBCS = QtGui.QSlider(self.gridLayoutWidget)
        self.HBCS.setMinimum(0)
        self.HBCS.setMaximum(120)
        self.HBCS.setProperty("value", 60)
        self.HBCS.setSliderPosition(60)
        self.HBCS.setOrientation(QtCore.Qt.Horizontal)
        self.HBCS.setObjectName(_fromUtf8("HBCS"))
        self.gridLayout.addWidget(self.HBCS, 3, 2, 1, 1)
        self.AvArBini = QtGui.QPushButton(self.gridLayoutWidget)
        self.AvArBini.setMaximumSize(QtCore.QSize(40, 16777215))
        self.AvArBini.setBaseSize(QtCore.QSize(0, 0))
        self.AvArBini.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 255);"))
        self.AvArBini.setObjectName(_fromUtf8("AvArBini"))
        self.gridLayout.addWidget(self.AvArBini, 13, 1, 1, 1)
        self.AvArBVal = QtGui.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.AvArBVal.setFont(font)
        self.AvArBVal.setStyleSheet(_fromUtf8("background-color: rgb(99, 99, 99);"))
        self.AvArBVal.setNumDigits(3)
        self.AvArBVal.setProperty("intValue", 60)
        self.AvArBVal.setObjectName(_fromUtf8("AvArBVal"))
        self.gridLayout.addWidget(self.AvArBVal, 13, 3, 1, 1)
        self.HBCini = QtGui.QPushButton(self.gridLayoutWidget)
        self.HBCini.setMaximumSize(QtCore.QSize(40, 16777215))
        self.HBCini.setBaseSize(QtCore.QSize(0, 0))
        self.HBCini.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.HBCini.setObjectName(_fromUtf8("HBCini"))
        self.gridLayout.addWidget(self.HBCini, 3, 1, 1, 1)
        self.HBCLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.HBCLabel.setObjectName(_fromUtf8("HBCLabel"))
        self.gridLayout.addWidget(self.HBCLabel, 2, 2, 1, 1)
        self.HBCVal = QtGui.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HBCVal.setFont(font)
        self.HBCVal.setStyleSheet(_fromUtf8("background-color: rgb(99, 99, 99);"))
        self.HBCVal.setNumDigits(3)
        self.HBCVal.setProperty("intValue", 60)
        self.HBCVal.setObjectName(_fromUtf8("HBCVal"))
        self.gridLayout.addWidget(self.HBCVal, 3, 3, 1, 1)
        self.AvArBLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.AvArBLabel.setObjectName(_fromUtf8("AvArBLabel"))
        self.gridLayout.addWidget(self.AvArBLabel, 12, 2, 1, 1)
        self.RBLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.RBLabel.setObjectName(_fromUtf8("RBLabel"))
        self.gridLayout.addWidget(self.RBLabel, 10, 2, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(InterfaceCommande)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 470, 258, 91))
        self.gridLayoutWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sourisY = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sourisY.setFont(font)
        self.sourisY.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        self.sourisY.setObjectName(_fromUtf8("sourisY"))
        self.gridLayout_2.addWidget(self.sourisY, 0, 0, 1, 1)
        self.sourisX = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sourisX.setFont(font)
        self.sourisX.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        self.sourisX.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.sourisX.setObjectName(_fromUtf8("sourisX"))
        self.gridLayout_2.addWidget(self.sourisX, 0, 2, 1, 1)
        self.MGLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLabel.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        self.MGLabel.setObjectName(_fromUtf8("MGLabel"))
        self.gridLayout_2.addWidget(self.MGLabel, 1, 0, 1, 1)
        self.InversionB = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.InversionB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.InversionB.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.InversionB.setObjectName(_fromUtf8("InversionB"))
        self.gridLayout_2.addWidget(self.InversionB, 0, 1, 1, 1)
        self.MDLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MDLabel.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        self.MDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MDLabel.setObjectName(_fromUtf8("MDLabel"))
        self.gridLayout_2.addWidget(self.MDLabel, 1, 2, 1, 1)
        self.MGini = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.MGini.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.MGini.setObjectName(_fromUtf8("MGini"))
        self.gridLayout_2.addWidget(self.MGini, 2, 0, 1, 1)
        self.MDini = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.MDini.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.MDini.setObjectName(_fromUtf8("MDini"))
        self.gridLayout_2.addWidget(self.MDini, 2, 2, 1, 1)
        self.Stopper = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.Stopper.setStyleSheet(_fromUtf8("background-color: rgb(255, 55, 55);"))
        self.Stopper.setObjectName(_fromUtf8("Stopper"))
        self.gridLayout_2.addWidget(self.Stopper, 2, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);"))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(InterfaceCommande)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 511, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.PortSerie = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.PortSerie.setMaxVisibleItems(1)
        self.PortSerie.setObjectName(_fromUtf8("PortSerie"))
        self.horizontalLayout.addWidget(self.PortSerie)
        self.Port = QtGui.QLabel(self.horizontalLayoutWidget)
        self.Port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Port.setBaseSize(QtCore.QSize(0, 0))
        self.Port.setAlignment(QtCore.Qt.AlignCenter)
        self.Port.setObjectName(_fromUtf8("Port"))
        self.horizontalLayout.addWidget(self.Port)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.vitesse = QtGui.QLabel(self.horizontalLayoutWidget)
        self.vitesse.setAlignment(QtCore.Qt.AlignCenter)
        self.vitesse.setObjectName(_fromUtf8("vitesse"))
        self.horizontalLayout.addWidget(self.vitesse)
        self.Vcom = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.Vcom.setObjectName(_fromUtf8("Vcom"))
        self.Vcom.addItem(_fromUtf8(""))
        self.Vcom.addItem(_fromUtf8(""))
        self.Vcom.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.Vcom)
        self.verticalLayoutWidget = QtGui.QWidget(InterfaceCommande)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 59, 131, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Connexion = QtGui.QPushButton(self.verticalLayoutWidget)
        self.Connexion.setStyleSheet(_fromUtf8("background-color: rgb(255, 121, 123);"))
        self.Connexion.setObjectName(_fromUtf8("Connexion"))
        self.verticalLayout.addWidget(self.Connexion)
        self.lineEditChaineEnvoi = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditChaineEnvoi.setObjectName(_fromUtf8("lineEditChaineEnvoi"))
        self.verticalLayout.addWidget(self.lineEditChaineEnvoi)
        self.Envoi = QtGui.QPushButton(self.verticalLayoutWidget)
        self.Envoi.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 255);"))
        self.Envoi.setObjectName(_fromUtf8("Envoi"))
        self.verticalLayout.addWidget(self.Envoi)
        self.verticalLayoutWidget_2 = QtGui.QWidget(InterfaceCommande)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(249, 59, 261, 111))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.receptionLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.receptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.receptionLabel.setObjectName(_fromUtf8("receptionLabel"))
        self.verticalLayout_2.addWidget(self.receptionLabel)
        self.textReception = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        self.textReception.setObjectName(_fromUtf8("textReception"))
        self.verticalLayout_2.addWidget(self.textReception)
        self.crepp = QtGui.QLabel(InterfaceCommande)
        self.crepp.setGeometry(QtCore.QRect(130, 80, 119, 59))
        self.crepp.setText(_fromUtf8(""))
        self.crepp.setPixmap(QtGui.QPixmap(_fromUtf8("../InterfaceFlo/logocrepp.jpg")))
        self.crepp.setObjectName(_fromUtf8("crepp"))

        self.retranslateUi(InterfaceCommande)
        QtCore.QObject.connect(self.RCS, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.RCVal.display)
        QtCore.QObject.connect(self.HBCS, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.HBCVal.display)
        QtCore.QObject.connect(self.RBS, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.RBVal.display)
        QtCore.QObject.connect(self.EBS, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ElevBVal.display)
        QtCore.QObject.connect(self.AvArBS, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.AvArBVal.display)
        QtCore.QObject.connect(self.PinceS, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.PinceVal.display)
        QtCore.QMetaObject.connectSlotsByName(InterfaceCommande)

    def retranslateUi(self, InterfaceCommande):
        InterfaceCommande.setWindowTitle(_translate("InterfaceCommande", "Interface Commande Raspibot", None))
        self.EBLabel.setText(_translate("InterfaceCommande", "Elevation Bras-8", None))
        self.RAZgeneral.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Remet servos et moteurs en position initiale</p></body></html>", None))
        self.RAZgeneral.setText(_translate("InterfaceCommande", "Init", None))
        self.RBini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Remet la rotation bras  en position médiane (60°)</p></body></html>", None))
        self.RBini.setText(_translate("InterfaceCommande", "Init", None))
        self.pinceini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Remet la pince en position médiane (60°)</p></body></html>", None))
        self.pinceini.setText(_translate("InterfaceCommande", "Init", None))
        self.ElevBini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Remet l\'elevation bras en position médiane (60°)</p></body></html>", None))
        self.ElevBini.setText(_translate("InterfaceCommande", "Init", None))
        self.RotCini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Remet la rotation camera à 60°</p></body></html>", None))
        self.RotCini.setText(_translate("InterfaceCommande", "Init", None))
        self.RAZLabel.setText(_translate("InterfaceCommande", "Remise à Zéro", None))
        self.RCLabel.setText(_translate("InterfaceCommande", "Rotation Cam-5", None))
        self.PinceLabel.setText(_translate("InterfaceCommande", "Pince-9", None))
        self.AvArBini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Remet Av/Ar bras en position médiane (60°)</p></body></html>", None))
        self.AvArBini.setText(_translate("InterfaceCommande", "Init", None))
        self.HBCini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Remet l\'elevation camera en position médiane (60°)</p></body></html>", None))
        self.HBCini.setText(_translate("InterfaceCommande", "Init", None))
        self.HBCLabel.setText(_translate("InterfaceCommande", "Haut/Bas Cam-4", None))
        self.AvArBLabel.setText(_translate("InterfaceCommande", "Av/Ar Bras-7", None))
        self.RBLabel.setText(_translate("InterfaceCommande", "Rotation Bras-6", None))
        self.sourisY.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:400;\">Visualisation moteur gauche</span></p></body></html>", None))
        self.sourisX.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:400;\">Visualisation moteur droit</span></p></body></html>", None))
        self.MGLabel.setText(_translate("InterfaceCommande", "Mot Gauche", None))
        self.InversionB.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Inversion moteurs (un en avant, l\'autre en arriere)</p></body></html>", None))
        self.InversionB.setText(_translate("InterfaceCommande", "Inverse", None))
        self.MDLabel.setText(_translate("InterfaceCommande", "MotDroit", None))
        self.MGini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Arrêt moteur gauche (position d\'attente)</p></body></html>", None))
        self.MGini.setText(_translate("InterfaceCommande", "Stop G", None))
        self.MDini.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Arret moteur Droit(position d\'attente)</p></body></html>", None))
        self.MDini.setText(_translate("InterfaceCommande", "Stop D", None))
        self.Stopper.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Arrêt des deux moteurs (position d\'attente)</p></body></html>", None))
        self.Stopper.setText(_translate("InterfaceCommande", "STOP", None))
        self.checkBox.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Passage de mode manuel (selectionné) en automatique(désélectionné)</p></body></html>", None))
        self.checkBox.setText(_translate("InterfaceCommande", " Manuel", None))
        self.Port.setText(_translate("InterfaceCommande", "Port", None))
        self.vitesse.setText(_translate("InterfaceCommande", "Vitesse", None))
        self.Vcom.setItemText(0, _translate("InterfaceCommande", "115200", None))
        self.Vcom.setItemText(1, _translate("InterfaceCommande", "38400", None))
        self.Vcom.setItemText(2, _translate("InterfaceCommande", "9600", None))
        self.Connexion.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Lancement de la connexion serie une fois fixés le port et la vitesse</p></body></html>", None))
        self.Connexion.setText(_translate("InterfaceCommande", "Activer Port", None))
        self.lineEditChaineEnvoi.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Champ d\'entrée de commande manuelle</p></body></html>", None))
        self.Envoi.setToolTip(_translate("InterfaceCommande", "<html><head/><body><p>Bouton d\'envoi pour commande manuelle</p></body></html>", None))
        self.Envoi.setText(_translate("InterfaceCommande", "Envoi", None))
        self.receptionLabel.setText(_translate("InterfaceCommande", "RECEPTION", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    InterfaceCommande = QtGui.QWidget()
    ui = Ui_InterfaceCommande()
    ui.setupUi(InterfaceCommande)
    InterfaceCommande.show()
    sys.exit(app.exec_())

